"""
One-shot backfill: ensure every document in bakasura-docs, hitl-charlie,
and news_articles has an `embedding` field (Vector, 768d) generated by
text-embedding-004 — the same model the rest of Saige's RAG uses.

Idempotent: skips docs that already have a non-empty `embedding`. Safe
to re-run after partial failures.

Usage:
    python backfill_embeddings.py                        # all three
    python backfill_embeddings.py bakasura-docs          # one
    python backfill_embeddings.py news_articles --force  # re-embed all
"""
from __future__ import annotations

import os
import sys
import time
from typing import Iterable, Optional

from dotenv import load_dotenv
load_dotenv()

from google.cloud import firestore
from google.cloud.firestore_v1.vector import Vector
from google.oauth2 import service_account
from langchain_google_genai import GoogleGenerativeAIEmbeddings

PROJECT = os.getenv("GOOGLE_CLOUD_PROJECT", "").strip()
CREDS_PATH = os.getenv("GOOGLE_APPLICATION_CREDENTIALS", "").strip()
DATABASE = os.getenv("FIRESTORE_DATABASE", "charlie").strip()
EMBED_MODEL = "models/text-embedding-004"
BATCH_SIZE = 100  # Firestore commit batch size (well under 500 limit)
EMBED_RPS_PAUSE = 0.05  # ~20 req/s — safe under default Google quota


# Per-collection text extraction. We don't touch existing fields (chunk_id,
# content_vector, etc.) — just add `embedding`.
def text_for_doc(coll_name: str, data: dict) -> str:
    if coll_name == "news_articles":
        # Title + description + content (strip HTML tags lightly)
        import re
        parts = [str(data.get("title") or ""), str(data.get("description") or "")]
        content = str(data.get("content") or "")
        # Strip HTML tags so embedding is on prose, not markup
        content = re.sub(r"<[^>]+>", " ", content)
        content = re.sub(r"\s+", " ", content)
        parts.append(content)
        text = " ".join(p for p in parts if p).strip()
        return text[:8000]  # text-embedding-004 supports up to 2048 tokens (~8k chars)
    # bakasura-docs and hitl-charlie store chunked PDF text under `content`
    return str(data.get("content") or "")[:8000]


def make_db():
    if CREDS_PATH:
        creds = service_account.Credentials.from_service_account_file(
            CREDS_PATH, scopes=["https://www.googleapis.com/auth/cloud-platform"]
        )
        return firestore.Client(project=PROJECT, database=DATABASE, credentials=creds)
    return firestore.Client(project=PROJECT, database=DATABASE)


def make_embedder():
    return GoogleGenerativeAIEmbeddings(model=EMBED_MODEL, project=PROJECT)


def backfill(coll_name: str, force: bool = False) -> dict:
    db = make_db()
    embedder = make_embedder()
    coll = db.collection(coll_name)

    total = coll.count().get()[0][0].value
    print(f"\n[{coll_name}] {total} total docs (force={force})")

    embedded = 0
    skipped = 0
    no_text = 0
    errors = 0
    batch = db.batch()
    batch_count = 0

    for snap in coll.stream():
        data = snap.to_dict() or {}

        # Skip if already has a usable embedding (unless forcing)
        if not force:
            existing = data.get("embedding")
            if existing is not None:
                # Vector type or non-empty list both count
                if hasattr(existing, "to_map_value") or (isinstance(existing, list) and existing):
                    skipped += 1
                    continue

        text = text_for_doc(coll_name, data)
        if not text or len(text) < 5:
            no_text += 1
            continue

        try:
            vec = embedder.embed_query(text)
        except Exception as e:
            print(f"  [{snap.id}] embed error: {e}")
            errors += 1
            time.sleep(0.5)
            continue

        if not vec:
            errors += 1
            continue

        batch.update(snap.reference, {"embedding": Vector(vec)})
        batch_count += 1
        embedded += 1

        if batch_count >= BATCH_SIZE:
            batch.commit()
            batch = db.batch()
            batch_count = 0
            print(f"  ...committed batch (running total embedded={embedded}, skipped={skipped})")
            time.sleep(EMBED_RPS_PAUSE)

    if batch_count > 0:
        batch.commit()

    print(f"[{coll_name}] done: embedded={embedded}, skipped={skipped}, "
          f"no_text={no_text}, errors={errors}")
    return {"embedded": embedded, "skipped": skipped, "no_text": no_text, "errors": errors}


def main(argv: list[str]):
    force = "--force" in argv
    args = [a for a in argv if not a.startswith("--")]

    targets = args or ["bakasura-docs", "hitl-charlie", "news_articles"]
    summary = {}
    for t in targets:
        try:
            summary[t] = backfill(t, force=force)
        except Exception as e:
            print(f"[{t}] FATAL: {e}")
            summary[t] = {"error": str(e)}

    print("\n=== Summary ===")
    for k, v in summary.items():
        print(f"  {k}: {v}")


if __name__ == "__main__":
    main(sys.argv[1:])
